In [1]:
import pandas as pd
import pickle
import nltk
import csv
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import krovetz
import numpy as np
from nltk.corpus import wordnet 
import re
from bs4 import BeautifulSoup
from html import unescape
from nltk.tokenize import word_tokenize

In [2]:
from collections import defaultdict


In [3]:
df=pd.read_csv('pcikle_to_csv.csv',encoding='utf-8')



In [4]:
df

Unnamed: 0 questionType        asin  \
0               0       yes/no  0594033926   
1               1       yes/no  0594033926   
2               2   open-ended  0594033926   
3               3       yes/no  0594033926   
4               4       yes/no  0594033926   
5               5       yes/no  0594033926   
6               6       yes/no  0594033926   
7               7   open-ended  0594033926   
8               8       yes/no  0594033926   
9               9   open-ended  0594033926   
10             10   open-ended  0972683275   
11             11       yes/no  0972683275   
12             12       yes/no  0972683275   
13             13       yes/no  0972683275   
14             14       yes/no  0972683275   
15             15       yes/no  0972683275   
16             16       yes/no  0972683275   
17             17   open-ended  0972683275   
18             18       yes/no  0972683275   
19             19       yes/no  0972683275   
20             20       yes/no  1394860919   
21             21       yes/no  1394860919   
22             22       yes/no  1394860919   
23             23       yes/no  1394860919   
24             24       yes/no  1394860919   
25             25       yes/no  1394860919   
26             26       yes/no  1394860919   
27             27       yes/no  1394860919   
28             28   open-ended  1394860919   
29             29       yes/no  1400532620   
...           ...          ...         ...   
28765       28765   open-ended  B000MUDI9S   
28766       28766   open-ended  B000MUDI9S   
28767       28767   open-ended  B000MUDI9S   
28768       28768       yes/no  B000MUQ8P4   
28769       28769   open-ended  B000MUQ8P4   
28770       28770   open-ended  B000MUQ8P4   
28771       28771       yes/no  B000MUQ8P4   
28772       28772       yes/no  B000MUQ8P4   
28773       28773   open-ended  B000MUQ8P4   
28774       28774       yes/no  B000MUQ8P4   
28775       28775       yes/no  B000MUQ8P4   
28776       28776   open-ended  B000MUQ8P4   
28777       28777       yes/no  B000MUQ8P4   
28778       28778       yes/no  B000MURAU6   
28779       28779   open-ended  B000MURAU6   
28780       28780       yes/no  B000MURAU6   
28781       28781   open-ended  B000MURAU6   
28782       28782   open-ended  B000MUT5AY   
28783       28783   open-ended  B000MUT5AY   
28784       28784   open-ended  B000MUT5AY   
28785       28785   open-ended  B000MUT5AY   
28786       28786       yes/no  B000MUT5AY   
28787       28787   open-ended  B000MUT5AY   
28788       28788   open-ended  B000MUT5AY   
28789       28789   open-ended  B000MUT5AY   
28790       28790       yes/no  B000MUT5AY   
28791       28791   open-ended  B000MUT5AY   
28792       28792   open-ended  B000MUV6BA   
28793       28793   open-ended  B000MUV6BA   
28794       28794   open-ended  B000MUV6BA   

                                                question answerType  \
0      Is this cover the one that fits the old nook c...          Y   
1                            Does it fit Nook GlowLight?          N   
2         Would it fit Nook 1st Edition? 4.9in x 7.7in ?        NaN   
3               Will this fit a Nook Color that's 5 x 8?          Y   
4       will this fit the Samsung Galaxy Tab 4 Nook 10.1          N   
5                             does it have a flip stand?          N   
6                            does this have a flip stand          ?   
7                                     also fits the HD+?        NaN   
8      Does it have 2 positions for the reader? Horiz...          Y   
9      Is there a closure mechanism? Bands, magnetic,...        NaN   
10                      how far out does the arm extend?        NaN   
11     can you mount a sound bar using the external "...          Y   
12     My TV has a VESA 200x200 bolt pattern and I ne...          Y   
13     my vizio has 200 ht x 600 width mounting holes...          ?   
14                                will it fit vizio tvs?          Y   
15            does

In [5]:
print("started cleaning data")
def remove_stopwords():
    stop = stopwords.words('english')
    pattern=r'(?i)\b((?:[a-z][\w-]+:(?:/{1,3}|[a-z0-9%])|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:\'".,<>?«»“”‘’]))';
    ks = krovetz.PyKrovetzStemmer()
    new_word_final = []
    for i in range(len(df2)):
        line = df2['description'].iloc[i]
        line = line.strip('\[ \]')
        match = re.findall(pattern, line)
        for m in match:
            url = m[0]
            line = line.replace(url, '')
        soup = BeautifulSoup(unescape(line), 'lxml')
        line = soup.text
        line = ' '.join([word.strip('; : ! * - \\ · . ® \® //') for word in line.split() if word not in (stop)])
        tokenizer = nltk.RegexpTokenizer(r"\w+")
        text = tokenizer.tokenize(line)
        check_pos = lambda pos: pos[:] in ['NN','NNP','CD','NNS', 'JJ','NNPS', 'VBD','POS']
        new_words = [x for (x, pos) in nltk.pos_tag(text) if check_pos(pos)]
#         new_words = line.split()
        new_word_final.append(krovetz_stem_word(new_words))
        print(i)
        

    print('completed descriptions')

    df['question_no_stopwords'] = df['question'].apply(lambda x: ' '.join([word for word in x.split() if word.lower() not in (stop)]))
    #del df['description']
    # del df['question']
    new_word_questions = []
    for i in range(len(df)):
        line = df['question_no_stopwords'].iloc[i]
        line = line.strip('\[ \]')
        match = re.findall(pattern, line)
        for m in match:
            line = line.replace(m[0], '')
        soup = BeautifulSoup(unescape(line), 'lxml')
        line = soup.text
        line = ' '.join([word.strip('; : ! * - \\ · . ® \® //') for word in line.split() if word not in (stop)])
        tokenizer = nltk.RegexpTokenizer(r"\w+")
        text = tokenizer.tokenize(line)
        check_pos = lambda pos: pos[:] in ['NN','NNP','CD','NNS', 'JJ','NNPS', 'VBD','POS']
        new_words = [x for (x, pos) in nltk.pos_tag(text) if check_pos(pos)]
#         new_words = line.split()
        new_word_questions.append(krovetz_stem_word(new_words))
    print('completed questions')
    return new_word_final,new_word_questions

started cleaning data


In [6]:
df2 = df.copy()
df2 = df2.loc[:, ~df2.columns.str.contains('^Unnamed')]
print(df2)

      questionType        asin  \
0           yes/no  0594033926   
1           yes/no  0594033926   
2       open-ended  0594033926   
3           yes/no  0594033926   
4           yes/no  0594033926   
5           yes/no  0594033926   
6           yes/no  0594033926   
7       open-ended  0594033926   
8           yes/no  0594033926   
9       open-ended  0594033926   
10      open-ended  0972683275   
11          yes/no  0972683275   
12          yes/no  0972683275   
13          yes/no  0972683275   
14          yes/no  0972683275   
15          yes/no  0972683275   
16          yes/no  0972683275   
17      open-ended  0972683275   
18          yes/no  0972683275   
19          yes/no  0972683275   
20          yes/no  1394860919   
21          yes/no  1394860919   
22          yes/no  1394860919   
23          yes/no  1394860919   
24          yes/no  1394860919   
25          yes/no  1394860919   
26          yes/no  1394860919   
27          yes/no  1394860919   
28      open-e

In [7]:
df2 = df2.drop_duplicates(subset = ["asin"])
print(df2)

      questionType        asin  \
0           yes/no  0594033926   
10      open-ended  0972683275   
20          yes/no  1394860919   
29          yes/no  1400532620   
34          yes/no  140053271X   
44          yes/no  1400501741   
54      open-ended  1400699169   
64          yes/no  1400599997   
74      open-ended  1400501466   
84      open-ended  8862936826   
93          yes/no  8918010656   
103     open-ended  9486350493   
110         yes/no  9573212919   
120     open-ended  9625993428   
125     open-ended  9876050885   
131         yes/no  9888002198   
140         yes/no  9966559760   
143     open-ended  9966569863   
150     open-ended  9966541551   
159         yes/no  9966694544   
162         yes/no  9966696482   
171         yes/no  9983891212   
181         yes/no  998504780X   
184     open-ended  9984988309   
189         yes/no  9985511476   
198         yes/no  9985609034   
205     open-ended  B000001OM5   
215         yes/no  B000001OM4   
221         ye

In [8]:
 df2 = df2.reset_index(drop=True)

In [9]:
df2

questionType        asin  \
0          yes/no  0594033926   
1      open-ended  0972683275   
2          yes/no  1394860919   
3          yes/no  1400532620   
4          yes/no  140053271X   
5          yes/no  1400501741   
6      open-ended  1400699169   
7          yes/no  1400599997   
8      open-ended  1400501466   
9      open-ended  8862936826   
10         yes/no  8918010656   
11     open-ended  9486350493   
12         yes/no  9573212919   
13     open-ended  9625993428   
14     open-ended  9876050885   
15         yes/no  9888002198   
16         yes/no  9966559760   
17     open-ended  9966569863   
18     open-ended  9966541551   
19         yes/no  9966694544   
20         yes/no  9966696482   
21         yes/no  9983891212   
22         yes/no  998504780X   
23     open-ended  9984988309   
24         yes/no  9985511476   
25         yes/no  9985609034   
26     open-ended  B000001OM5   
27         yes/no  B000001OM4   
28         yes/no  B00000I9HF   
29         yes/no  B00000J08Q   
...           ...         ...   
2580   open-ended  B000MKKTJK   
2581   open-ended  B000MKUQBG   
2582   open-ended  B000MKWDJE   
2583       yes/no  B000MLHMAS   
2584   open-ended  B000MLL6QE   
2585       yes/no  B000MMWBK8   
2586       yes/no  B000MND1B0   
2587   open-ended  B000MOF3IS   
2588   open-ended  B000MP831G   
2589   open-ended  B000MPMHD6   
2590       yes/no  B000MPMHK4   
2591       yes/no  B000MPO8R4   
2592       yes/no  B000MPPY2M   
2593   open-ended  B000MQEHCO   
2594   open-ended  B000MQJ19S   
2595   open-ended  B000MQJ1DO   
2596   open-ended  B000MRN0LM   
2597   open-ended  B000MSC4Z4   
2598       yes/no  B000MSC4YK   
2599   open-ended  B000MSDL6K   
2600   open-ended  B000MSS5YS   
2601   open-ended  B000MT7RW8   
2602   open-ended  B000MTEER4   
2603       yes/no  B000MTP9PU   
2604   open-ended  B000MU4LX0   
2605   open-ended  B000MUDI9S   
2606       yes/no  B000MUQ8P4   
2607       yes/no  B000MURAU6   
2608   open-ended  B000MUT5AY   
2609   open-ended  B000MUV6BA   

                                               question answerType  \
0     Is this cover the one that fits the old nook c...          Y   
1                      how far out does the arm extend?        NaN   
2     Hi, does it work with MacBook Air 13.3" latest...          ?   
3                   Does this item come with a charger?          ?   
4                      Does it have a slot for sd card?          ?   
5          Can I port my Kindle books to this platform?          ?   
6     How easy is this to use in direct sunlight? gl...        NaN   
7                                   is it user friendly          Y   
8                           Nook Tablet or Kindle fire?        NaN   
9     Left-handed compatibility? Does anyone know if...        NaN   
10    Can be run on Apple Computer with Graphic card...          N   
11    i will like to know does it save the file in a...        NaN   
12    It won't burn disks...is there a driver I can ...          Y   
13                                                skype        NaN   
14    Love the card, works great with 1520 but I rec...        NaN   
15                             Will this work in Italy?          Y   
16         Hi. Does this work for Samsung Galaxy note2?          Y   
17    Will this card work with other devices or gopr...        NaN   
18    Can this be used with other android smartphone...        NaN   
19    Is this sd card compatible with Samsung Galaxy...          Y   
20                 Will this work in a Samsung S4 MINI?          Y   
21                      is mini hdmi same as micro hdmi          ?   
22    I have a question about this product. is that ...          Y   
23                      What's the length of this cord?        NaN   
24            will this card work in my 1450 LMT model?          Y   
25    Does this also support lower resolution...exam...          Y   
26    How do you know its working in there? I bought...        NaN  

In [10]:
df2 = df2.loc[:, ~df2.columns.str.contains('^Unnamed')]

In [11]:
df2

questionType        asin  \
0          yes/no  0594033926   
1      open-ended  0972683275   
2          yes/no  1394860919   
3          yes/no  1400532620   
4          yes/no  140053271X   
5          yes/no  1400501741   
6      open-ended  1400699169   
7          yes/no  1400599997   
8      open-ended  1400501466   
9      open-ended  8862936826   
10         yes/no  8918010656   
11     open-ended  9486350493   
12         yes/no  9573212919   
13     open-ended  9625993428   
14     open-ended  9876050885   
15         yes/no  9888002198   
16         yes/no  9966559760   
17     open-ended  9966569863   
18     open-ended  9966541551   
19         yes/no  9966694544   
20         yes/no  9966696482   
21         yes/no  9983891212   
22         yes/no  998504780X   
23     open-ended  9984988309   
24         yes/no  9985511476   
25         yes/no  9985609034   
26     open-ended  B000001OM5   
27         yes/no  B000001OM4   
28         yes/no  B00000I9HF   
29         yes/no  B00000J08Q   
...           ...         ...   
2580   open-ended  B000MKKTJK   
2581   open-ended  B000MKUQBG   
2582   open-ended  B000MKWDJE   
2583       yes/no  B000MLHMAS   
2584   open-ended  B000MLL6QE   
2585       yes/no  B000MMWBK8   
2586       yes/no  B000MND1B0   
2587   open-ended  B000MOF3IS   
2588   open-ended  B000MP831G   
2589   open-ended  B000MPMHD6   
2590       yes/no  B000MPMHK4   
2591       yes/no  B000MPO8R4   
2592       yes/no  B000MPPY2M   
2593   open-ended  B000MQEHCO   
2594   open-ended  B000MQJ19S   
2595   open-ended  B000MQJ1DO   
2596   open-ended  B000MRN0LM   
2597   open-ended  B000MSC4Z4   
2598       yes/no  B000MSC4YK   
2599   open-ended  B000MSDL6K   
2600   open-ended  B000MSS5YS   
2601   open-ended  B000MT7RW8   
2602   open-ended  B000MTEER4   
2603       yes/no  B000MTP9PU   
2604   open-ended  B000MU4LX0   
2605   open-ended  B000MUDI9S   
2606       yes/no  B000MUQ8P4   
2607       yes/no  B000MURAU6   
2608   open-ended  B000MUT5AY   
2609   open-ended  B000MUV6BA   

                                               question answerType  \
0     Is this cover the one that fits the old nook c...          Y   
1                      how far out does the arm extend?        NaN   
2     Hi, does it work with MacBook Air 13.3" latest...          ?   
3                   Does this item come with a charger?          ?   
4                      Does it have a slot for sd card?          ?   
5          Can I port my Kindle books to this platform?          ?   
6     How easy is this to use in direct sunlight? gl...        NaN   
7                                   is it user friendly          Y   
8                           Nook Tablet or Kindle fire?        NaN   
9     Left-handed compatibility? Does anyone know if...        NaN   
10    Can be run on Apple Computer with Graphic card...          N   
11    i will like to know does it save the file in a...        NaN   
12    It won't burn disks...is there a driver I can ...          Y   
13                                                skype        NaN   
14    Love the card, works great with 1520 but I rec...        NaN   
15                             Will this work in Italy?          Y   
16         Hi. Does this work for Samsung Galaxy note2?          Y   
17    Will this card work with other devices or gopr...        NaN   
18    Can this be used with other android smartphone...        NaN   
19    Is this sd card compatible with Samsung Galaxy...          Y   
20                 Will this work in a Samsung S4 MINI?          Y   
21                      is mini hdmi same as micro hdmi          ?   
22    I have a question about this product. is that ...          Y   
23                      What's the length of this cord?        NaN   
24            will this card work in my 1450 LMT model?          Y   
25    Does this also support lower resolution...exam...          Y   
26    How do you know its working in there? I bought...        NaN  

In [12]:
def krovetz_stem_word(word):
    ks = krovetz.PyKrovetzStemmer()
    stemmed_list = []
    for i in word:
        try:
            stemmed_list.append(ks.stem(i))
        except:
            print(i)
            stemmed_list.append(i)
    return stemmed_list
        



In [13]:
cleaned_words,cleaned_questions = remove_stopwords()


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
Canonís
whatís
whatís
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
Itís
whatís
whatís
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
28º
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
2

1751
1752
1753
1754
1755
1756
1757
1758
1759
1760
1761
1762
1763
1764
1765
1766
1767
1768
1769
1770
1771
1772
1773
1774
1775
1776
1777
1778
1779
1780
1781
1782
1783
1784
1785
1786
1787
1788
1789
1790
1791
1792
1793
1794
1795
1796
1797
1798
1799
1800
1801
1802
1803
1804
1805
1806
1807
1808
1809
1810
1811
1812
1813
1814
1815
1816
1817
1818
1819
1820
1821
1822
1823
1824
1825
1826
1827
1828
1829
1830
1831
1832
1833
1834
1835
1836
1837
1838
1839
1840
1841
1842
1843
1844
1845
1846
1847
1848
1849
1850
1851
1852
1853
1854
1855
1856
1857
1858
1859
1860
1861
1862
1863
1864
1865
1866
1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950


In [14]:
cleaned_words

[['dessin',
  'cover',
  'noir',
  'nook',
  'tablet',
  'e',
  'reader',
  'style',
  'able',
  'fit',
  'standard',
  'nook',
  'color',
  'nook',
  'tablet',
  'dessin',
  'cover',
  'noir',
  'cover',
  'nook',
  'tablet',
  'glaze',
  'exterior',
  'faux',
  'provide',
  'soft',
  'durable',
  'protection',
  'a',
  'leather',
  'slide',
  'pocket',
  'nook',
  'color',
  'cover',
  'e',
  'reader',
  'place',
  'nook',
  'color',
  'tablet',
  'cover',
  'let',
  'nook',
  'safe',
  'read',
  'carry',
  'hand',
  'backpack',
  'tote',
  'bag',
  'briefcase',
  '3',
  'point',
  'clip',
  'mechanism',
  'dessin',
  'cover',
  'noir',
  'nook',
  'tablet',
  'secure',
  'hold',
  'e',
  'reader',
  'e',
  'reader',
  'nook',
  'color',
  'cover',
  'easy',
  'access',
  'device',
  's',
  'port',
  'control'],
 ['videosecu',
  'tv',
  'mount',
  'solution',
  '22',
  '47',
  'lcd',
  'led',
  'plasma',
  'tv',
  'led',
  '55',
  'vesa',
  '600x400mm',
  '24',
  'x16',
  '400x400mm'

In [15]:
cleaned_questions

[['one', 'old', 'nook', 'color', '8x5'],
 ['fit', 'nook', 'glowlight'],
 ['nook', '1st', 'edition', '4', '9in', 'x', '7', '7in'],
 ['fit', 'nook', 'color', '5', 'x', '8'],
 ['fit', 'samsung', '4', 'nook', '10', '1'],
 ['flip', 'stand'],
 ['flip', 'stand'],
 ['hd'],
 ['2', 'position', 'horizontal', 'vertical', 'thank', 'kwod'],
 ['closure', 'mechanism', 'magnetic', 'etc'],
 ['arm', 'extend'],
 ['mount',
  'sound',
  'bar',
  'external',
  'stick',
  'arms',
  'lcd',
  'monitor',
  '27',
  'inch'],
 ['tv',
  'vesa',
  '200x200',
  'bolt',
  'pattern',
  '24',
  'inch',
  'extension',
  'wall',
  'mount',
  'fit',
  'bolt',
  'pattern'],
 ['vizio', '200', 'ht', 'x', '600', 'width', 'hole', 'handle'],
 ['fit', 'vizio', 'tvs'],
 ['work', '39', 'inch', 'magnavox', 'tv'],
 ['use', 'tv', 'vesa', '100', 'x', '100'],
 ['mount',
  '32',
  'vizio',
  'bolt',
  '20',
  'apart',
  'bracket',
  'fit',
  'last',
  'mount',
  'bought',
  'want',
  'buy',
  'extension'],
 ['work', 'viso', 'vx37l'],
 ['v

In [16]:
DF = {}

print("started tfidf data")

started tfidf data


In [17]:
def creating_columns():
    columns_tfidf = set()
    for row in cleaned_words:
        for word in row:
            columns_tfidf.add(word.lower())
    print('----------------------------------------')
    print(len(cleaned_words))
    print(len(columns_tfidf))
    print('=========================================')
    return columns_tfidf

In [18]:
def cal_doc_freq(columns_tfidf):
    # DF = {}
    for word in columns_tfidf:
        for i in range(len(cleaned_questions)):
            if (word in cleaned_questions[i]):
                try:
                    DF[word].add(i)
                except:
                    DF[word] = {i}
    for i in DF:
        DF[i] = len(DF[i])
    return DF


In [19]:
def word_doc_freq(word):
    c = 0
    try:
        c = DF[word]
    except:
        pass
    return c


In [20]:
def cal_inv_doc_freq(columns_tfidf):
    cal_doc_freq(columns_tfidf)
    iDF = {}
    for i in DF:
        iDF[i] = np.log(len(cleaned_questions)/ (DF[i] + 1)) #removed +1 from the numerator
    return iDF

In [21]:
def term_freq():
    term_freq_dict = dict()
    print("inside term_freq",len(cleaned_questions))
    for index in range(len(cleaned_questions)):
        for word in columns_tfidf:
            if word in cleaned_questions[index]:
                term_freq_dict.setdefault(index, []).append((word, cleaned_questions[index].count(word)/len(cleaned_questions[index])))
    print("inside term_freq",len(term_freq_dict))
    return term_freq_dict

In [22]:
def cal_tf_idf():
    tf_idf = dict()
    for key, value in term_freq_dict.items():
        for val in value:
            tf_idf.setdefault(key, []).append((val[0], iDF[val[0]] * val[1]))
    return tf_idf

In [23]:
columns_tfidf = creating_columns()

----------------------------------------
2610
14352


In [24]:
columns_tfidf

{'tlp602',
 'cd300',
 'd3',
 'breakfast',
 'cafeteria',
 'kg',
 'win95',
 'secret',
 '160x120',
 'emc',
 'rm6750',
 'opteka',
 'sd20',
 'jb00100',
 'generator',
 '12',
 'fox',
 'bulb',
 'moving',
 'ser0047',
 'magnetic',
 'interface',
 'upper',
 '9100',
 'long',
 'switzerland',
 'fidelity',
 'dynasync',
 'fdtv2',
 'commentary',
 '32mm',
 'nfit',
 'cetrex',
 'unrecognizable',
 'motorist',
 '125',
 'figures',
 'airware',
 'capacitive',
 'portrait',
 'points',
 'end',
 'warnaway',
 'ht227s',
 'cs55',
 's4666w',
 'lite',
 'lxt323',
 '13',
 'review',
 '770',
 '408',
 '2003',
 'showcase',
 'supersteadyshot',
 'iptusb',
 'rent',
 'remover',
 'itemdoesnotexistdonotbuyittttttttttt',
 'e63pr',
 '20th',
 'pose',
 'flatter',
 'bookshelf',
 'macropower',
 'audio',
 'crater',
 'bell',
 'headpad',
 'walkman______this',
 'pizza',
 'cx7330',
 'idrop',
 'edit',
 'h50',
 'ferro',
 'thorough',
 '85',
 't5320',
 'wand',
 '800mbps',
 'champagne',
 'actual',
 '103188',
 'spider',
 'undraped',
 'stoesz',
 '42

In [25]:
iDF = cal_inv_doc_freq(columns_tfidf)

In [26]:
iDF

{'cd300': 9.169344751272662,
 'd3': 8.476197570712717,
 'secret': 8.881662678820883,
 'rm6750': 9.169344751272662,
 'opteka': 8.881662678820883,
 'generator': 8.188515498260937,
 '12': 5.114665445442994,
 'bulb': 7.049081215072572,
 'moving': 9.169344751272662,
 'magnetic': 7.870061767142402,
 'interface': 7.009860501919291,
 'upper': 8.881662678820883,
 'long': 5.735357546787517,
 'switzerland': 9.169344751272662,
 'fidelity': 8.658519127506672,
 '125': 8.476197570712717,
 'portrait': 6.109073956581101,
 'points': 9.169344751272662,
 'end': 5.205362006913806,
 's4666w': 9.574809859380828,
 'lite': 8.188515498260937,
 '13': 6.5302874216574045,
 'review': 5.377607911719019,
 '770': 8.658519127506672,
 '2003': 6.802221137141046,
 'rent': 8.476197570712717,
 'pose': 9.574809859380828,
 'bookshelf': 7.434743695884556,
 'audio': 4.493405494396364,
 'edit': 7.22343460221735,
 '85': 7.559906838838563,
 'wand': 9.574809859380828,
 'actual': 5.924151618087089,
 'numbers': 7.495368317700992,
 's

In [27]:
term_freq_dict = term_freq()


inside term_freq 28795
inside term_freq 28613


In [28]:
term_freq_dict

{0: [('old', 0.2), ('one', 0.2), ('color', 0.2), ('nook', 0.2)],
 1: [('nook', 0.3333333333333333), ('fit', 0.3333333333333333)],
 2: [('9in', 0.125),
  ('edition', 0.125),
  ('x', 0.125),
  ('1st', 0.125),
  ('7in', 0.125),
  ('nook', 0.125),
  ('7', 0.125),
  ('4', 0.125)],
 3: [('x', 0.16666666666666666),
  ('color', 0.16666666666666666),
  ('nook', 0.16666666666666666),
  ('8', 0.16666666666666666),
  ('fit', 0.16666666666666666),
  ('5', 0.16666666666666666)],
 4: [('10', 0.16666666666666666),
  ('samsung', 0.16666666666666666),
  ('nook', 0.16666666666666666),
  ('1', 0.16666666666666666),
  ('fit', 0.16666666666666666),
  ('4', 0.16666666666666666)],
 5: [('flip', 0.5), ('stand', 0.5)],
 6: [('flip', 0.5), ('stand', 0.5)],
 7: [('hd', 1.0)],
 8: [('thank', 0.16666666666666666),
  ('2', 0.16666666666666666),
  ('vertical', 0.16666666666666666),
  ('position', 0.16666666666666666),
  ('horizontal', 0.16666666666666666)],
 9: [('magnetic', 0.25),
  ('etc', 0.25),
  ('closure', 0.25

In [29]:
tf_idf = cal_tf_idf()

In [30]:
tf_idf

{0: [('old', 0.8692757240593916),
  ('one', 0.5940377514818785),
  ('color', 1.0770310234708804),
  ('nook', 1.4264925648023246)],
 1: [('nook', 2.3774876080038743), ('fit', 0.9342914345137416)],
 2: [('9in', 1.1968512324226035),
  ('edition', 0.9536124637906893),
  ('x', 0.6350714042625022),
  ('1st', 0.922198160255576),
  ('7in', 1.1968512324226035),
  ('nook', 0.8915578530014528),
  ('7', 0.5480793314315617),
  ('4', 0.47368092471652545)],
 3: [('x', 0.8467618723500029),
  ('color', 0.8975258528924003),
  ('nook', 1.1887438040019371),
  ('8', 0.6161790129335314),
  ('fit', 0.4671457172568708),
  ('5', 0.637039536759199)],
 4: [('10', 0.7813712023257584),
  ('samsung', 0.8729198530913895),
  ('nook', 1.1887438040019371),
  ('1', 0.5703461941127872),
  ('fit', 0.4671457172568708),
  ('4', 0.6315745662887006)],
 5: [('flip', 3.7799534194192814), ('stand', 3.0785415878837306)],
 6: [('flip', 3.7799534194192814), ('stand', 3.0785415878837306)],
 7: [('hd', 5.180360704708389)],
 8: [('tha

In [31]:

print("ending tfidf data")

ending tfidf data


In [32]:
print("started cosine  distance")
## cal the tf-idf matrix :

# sorted(columns_tfidf)
print(len(columns_tfidf))
columns = list(columns_tfidf)

started cosine  distance
14352


In [33]:
sorted(columns)

['0',
 '00',
 '000',
 '00001',
 '000027',
 '00030',
 '000gs',
 '000hz',
 '000mm',
 '000mw',
 '000w',
 '000x',
 '001',
 '0013803046137',
 '002',
 '0025215281020',
 '003',
 '0033',
 '004',
 '00496',
 '005',
 '0050644291371',
 '00579',
 '006',
 '008',
 '009',
 '00in',
 '01',
 '010',
 '0106',
 '013803044027',
 '0183',
 '01961',
 '01en',
 '02',
 '024',
 '03',
 '03067',
 '032',
 '033',
 '03424',
 '03m',
 '04',
 '0400',
 '0403',
 '048',
 '05',
 '050',
 '05b',
 '06',
 '0625',
 '07',
 '0700',
 '072',
 '079000323020shipping',
 '08',
 '080',
 '0814',
 '0815',
 '085896626688',
 '096',
 '0a',
 '0d',
 '0db',
 '0gb',
 '0ghz',
 '0l',
 '0lux',
 '0m',
 '0mm',
 '0mp',
 '0r',
 '0screen',
 '0se',
 '0v',
 '0x',
 '0x3',
 '1',
 '10',
 '100',
 '1000',
 '10000',
 '100004',
 '100010c',
 '100044c',
 '100054c',
 '1000base',
 '1000c',
 '1000fn',
 '1000lbs',
 '1000m',
 '1000ma',
 '1000mb',
 '1000mbps',
 '1000mm',
 '1000n',
 '1000nm',
 '1000th',
 '1000va',
 '1000x',
 '1000yds',
 '1001d',
 '1001z',
 '100base',
 '100ba

In [34]:
D = np.zeros((len(cleaned_questions), len(columns_tfidf)))
print(D)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [35]:
D.shape

(28795, 14352)

In [36]:
for key,values in tf_idf.items():
    # print(key)
    # print(values)
    # print("i",i)
    for v in values:
        # print(v)
        try:
            # print("inside try")
            ind = columns.index(v[0])
            # print(v[0])
            # print(ind)
            D[key][ind] = v[1]
            # print(D[key][ind])
        except:
            # print("in except")
            pass

In [37]:
print(D)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [38]:
max(D[7])

5.180360704708389

In [39]:
def gen_vector(tokens):
    Q = np.zeros((len(columns)))

    counter = Counter(tokens)
    words_count = len(tokens)

    query_weights = {}

    for token in np.unique(tokens):

        tf = counter[token] / words_count
        df = word_doc_freq(token)
        idf = np.log((len(cleaned_questions)) / (df + 1))

        try:
            ind = columns.index(token.lower())
            Q[ind] = tf * idf
            print(ind)
        except:
            pass
    return Q

In [40]:
def cosine_sim(a, b):
    cos_sim = np.dot(a, b)/((np.linalg.norm(a)*np.linalg.norm(b))+1)
    return cos_sim

In [41]:
def cosine_similarity(k1, query):
    print("Cosine Similarity")
#     preprocessed_query = preprocess(query)
#     tokens = word_tokenize(str(preprocessed_query))

    print("\nQuery:", query)
#     print("")
#     print(tokens)

    d_cosines = []

    query_vector = gen_vector(query)
    print(query_vector)
    
    
    print("len",len(query_vector))
    for d in D:
        d_cosines.append(cosine_sim(query_vector, d))
        
        
    out=dict()
    for i in range(len(d_cosines)):
        out[i]=d_cosines[i]
        
    out= dict(sorted(out.items(), key=lambda item: item[1]))

#     print(d_cosines)
#     out = np.array(d_cosines).argsort()
#     out=list(out)
#     out=out[-10:]


    print("")
    print(out)
    
    ques=set()
    
    for x in list(reversed(list(out)))[0:50]:
        ques.add(df['question'][x])

    ques=list(ques)
    print(ques[:20])
    
    
#     for k,v in out.items():
#         print(df['question'][k])


In [42]:
from collections import Counter

In [43]:
Query = cleaned_words[120]
cosine_similarity(10,Query)
print(Query)

Cosine Similarity

Query: ['canon', '75', '300mm', 'f', '4', '5', '6', 'is', 'usm', 'telephoto', 'zoom', 'canon', 'slr', 'camera', '75', '300mm', 'zoom', 'lens', '4', '0', '5', '6', 'image', 'stabilizer', 'optical', 'system', 'construction', 'ef', '75', '300', 'mm', 'f', '4', '5', '6', 'iii', 'usm', 'difference', 'dc', 'motor', 'usm', 'drive', 'af']
3444
4269
13020
12008
12207
767
9014
4470
10631
2077
7585
10430
11703
9946
7112
10806
14348
557
13770
9723
10366
8092
13406
3095
1940
2154
9387
6631
3137
[0. 0. 0. ... 0. 0. 0.]
len 14352

{0: 0.0, 1: 0.0, 5: 0.0, 6: 0.0, 7: 0.0, 8: 0.0, 9: 0.0, 10: 0.0, 11: 0.0, 12: 0.0, 13: 0.0, 14: 0.0, 15: 0.0, 16: 0.0, 17: 0.0, 18: 0.0, 19: 0.0, 20: 0.0, 21: 0.0, 22: 0.0, 23: 0.0, 24: 0.0, 25: 0.0, 26: 0.0, 27: 0.0, 28: 0.0, 29: 0.0, 30: 0.0, 31: 0.0, 32: 0.0, 33: 0.0, 34: 0.0, 35: 0.0, 36: 0.0, 37: 0.0, 38: 0.0, 39: 0.0, 40: 0.0, 41: 0.0, 42: 0.0, 43: 0.0, 44: 0.0, 45: 0.0, 46: 0.0, 47: 0.0, 48: 0.0, 49: 0.0, 50: 0.0, 51: 0.0, 53: 0.0, 54: 0.0, 55: 0.

In [44]:
print(columns.index("mini"))

8878


In [45]:
print(columns.index("display"))

13978


In [46]:
print(columns.index("port"))

4467


In [47]:
print(columns.index("vga"))

2723


In [48]:
print(columns.index("cable"))

5583


In [49]:
print(columns.index("adapter"))

5777


In [50]:
print(columns.index("monitor"))

9661


In [51]:
print(columns.index("projector"))

9910


In [52]:
print(columns.index("macbook"))

8408


In [53]:
print(columns.index("air"))

3169


In [54]:
print(columns.index("pro"))

4085


In [55]:
print(gen_vector)

<function gen_vector at 0x000001EA5BA7F268>


In [56]:
x=gen_vector

In [57]:
x

<function __main__.gen_vector(tokens)>